APP_VERSION = "0.2.2"
APP_NAME = "Dad Image Tool"
BRAND_NAME = "D.A.D."
BRAND_FULL_NAME = "Dad's Automated Downloader"
TAGLINE = "Download • Archive • Deliver"
APP_DISPLAY_NAME = f"{BRAND_NAME} — {APP_NAME}"
GITHUB_REPOSITORY = "Necropolite/-Dad-Image-Tool"
RELEASE_ASSET_NAME = "Dad-Image-Tool.exe"
